/**
 * Aethos Document Control System - Mock Data Generator
 * 
 * Realistic demo data for prototype demonstrations
 */

import {
  DocumentLibrary,
  ControlledDocument,
  DocumentVersion,
  ApprovalWorkflow,
  ApprovalStage,
  DocumentAcknowledgement,
  ComplianceGap,
  DemoUser,
  DocumentStatus,
  DocumentType,
  LibraryType,
  ComplianceStandard,
  ApprovalStageType,
  UserRole,
  AcknowledgementStatus,
  HealthScoreLevel,
} from '../types/document-control.types';

// ============================================================================
// DEMO USERS
// ============================================================================

export const DEMO_USERS: DemoUser[] = [
  {
    id: 'user-1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@aethos-demo.com',
    role: UserRole.DOCUMENT_MANAGER,
    department: 'Human Resources',
  },
  {
    id: 'user-2',
    name: 'Mike Torres',
    email: 'mike.torres@aethos-demo.com',
    role: UserRole.APPROVER,
    department: 'Information Technology',
  },
  {
    id: 'user-3',
    name: 'Jane Doe',
    email: 'jane.doe@aethos-demo.com',
    role: UserRole.APPROVER,
    department: 'Legal',
  },
  {
    id: 'user-4',
    name: 'John Smith',
    email: 'john.smith@aethos-demo.com',
    role: UserRole.APPROVER,
    department: 'Executive',
  },
  {
    id: 'user-5',
    name: 'Emily Chen',
    email: 'emily.chen@aethos-demo.com',
    role: UserRole.CONTRIBUTOR,
    department: 'Quality Assurance',
  },
  {
    id: 'user-6',
    name: 'David Park',
    email: 'david.park@aethos-demo.com',
    role: UserRole.REVIEWER,
    department: 'Operations',
  },
  {
    id: 'user-7',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@aethos-demo.com',
    role: UserRole.VIEWER,
    department: 'Finance',
  },
  {
    id: 'user-8',
    name: 'Robert Martinez',
    email: 'robert.martinez@aethos-demo.com',
    role: UserRole.CONTRIBUTOR,
    department: 'Compliance',
  },
];

// ============================================================================
// DOCUMENT LIBRARIES
// ============================================================================

export const MOCK_LIBRARIES: DocumentLibrary[] = [
  {
    id: 'lib-1',
    tenantId: 'demo-tenant',
    name: 'HR Policies & Procedures',
    description: 'Human Resources policies, SOPs, and employee documentation',
    type: LibraryType.HR,
    complianceStandard: ComplianceStandard.ISO_9001,
    numberingPrefix: 'SOP-HR',
    numberingPattern: '{prefix}-{year}-{sequence:3}',
    currentSequence: 12,
    managers: ['user-1'],
    allowedRoles: [UserRole.DOCUMENT_MANAGER, UserRole.APPROVER, UserRole.CONTRIBUTOR, UserRole.VIEWER],
    isPrivate: false,
    requireAcknowledgement: true,
    defaultRetentionDays: 2555, // 7 years
    autoArchiveExpired: true,
    allowPdfConversion: true,
    createdBy: 'user-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-02-28'),
    documentCount: 18,
  },
  {
    id: 'lib-2',
    tenantId: 'demo-tenant',
    name: 'IT Security & Governance',
    description: 'Information security policies, data protection, and IT procedures',
    type: LibraryType.SECURITY,
    complianceStandard: ComplianceStandard.SOC_2,
    numberingPrefix: 'POL-IT',
    numberingPattern: '{prefix}-{year}-{sequence:3}',
    currentSequence: 25,
    managers: ['user-2'],
    allowedRoles: [UserRole.DOCUMENT_MANAGER, UserRole.APPROVER, UserRole.CONTRIBUTOR],
    isPrivate: true,
    requireAcknowledgement: true,
    defaultRetentionDays: 1825, // 5 years
    autoArchiveExpired: true,
    allowPdfConversion: true,
    createdBy: 'user-2',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2026-03-10'),
    documentCount: 24,
  },
  {
    id: 'lib-3',
    tenantId: 'demo-tenant',
    name: 'Quality Management System',
    description: 'ISO 9001 quality documentation, work instructions, and specifications',
    type: LibraryType.QUALITY_MANAGEMENT,
    complianceStandard: ComplianceStandard.ISO_9001,
    numberingPrefix: 'QMS',
    numberingPattern: '{prefix}-{year}-{sequence:3}',
    currentSequence: 8,
    managers: ['user-5'],
    allowedRoles: [UserRole.DOCUMENT_MANAGER, UserRole.APPROVER, UserRole.CONTRIBUTOR, UserRole.REVIEWER],
    isPrivate: false,
    requireAcknowledgement: true,
    defaultRetentionDays: 3650, // 10 years
    autoArchiveExpired: false,
    allowPdfConversion: true,
    createdBy: 'user-5',
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2026-03-01'),
    documentCount: 7,
  },
  {
    id: 'lib-4',
    tenantId: 'demo-tenant',
    name: 'General Documents',
    description: 'Miscellaneous documents without specific compliance requirements',
    type: LibraryType.GENERAL,
    complianceStandard: ComplianceStandard.NONE,
    numberingPrefix: 'DOC',
    numberingPattern: '{prefix}-{year}-{sequence:3}',
    currentSequence: 42,
    managers: ['user-1', 'user-2'],
    allowedRoles: [UserRole.DOCUMENT_MANAGER, UserRole.APPROVER, UserRole.CONTRIBUTOR, UserRole.REVIEWER, UserRole.VIEWER],
    isPrivate: false,
    requireAcknowledgement: false,
    autoArchiveExpired: false,
    allowPdfConversion: true,
    createdBy: 'user-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-03-14'),
    documentCount: 38,
  },
];

// ============================================================================
// CONTROLLED DOCUMENTS
// ============================================================================

export const MOCK_DOCUMENTS: ControlledDocument[] = [
  // HR Library - Published Documents
  {
    id: 'doc-1',
    libraryId: 'lib-1',
    tenantId: 'demo-tenant',
    documentNumber: 'SOP-HR-2026-001',
    title: 'Remote Work Policy',
    type: DocumentType.POLICY,
    status: DocumentStatus.PUBLISHED,
    currentVersion: '3.2',
    versionId: 'ver-1-3',
    category: 'Workplace Policies',
    tags: ['remote work', 'hybrid', 'flexibility', 'work from home'],
    department: 'Human Resources',
    owner: 'user-1',
    contributors: ['user-1', 'user-4'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-001',
    sourceFileName: 'Remote_Work_Policy_v3.2.docx',
    sourceFileUrl: 'https://demo-sharepoint.com/sites/hr/Remote_Work_Policy_v3.2.docx',
    fileSize: 245000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    aiSuggestedTags: ['remote work', 'hybrid', 'telecommuting', 'workspace flexibility'],
    aiSuggestedCategory: 'Workplace Policies',
    aiContentSummary: 'This policy defines eligibility, expectations, and guidelines for employees working remotely or in hybrid arrangements. Covers equipment, security, communication, and performance management.',
    complianceStandard: ComplianceStandard.ISO_9001,
    requiresApproval: true,
    requiresAcknowledgement: true,
    approvedDate: new Date('2026-02-15'),
    publishedDate: new Date('2026-02-15'),
    nextReviewDate: new Date('2027-02-15'),
    relatedDocuments: ['doc-2', 'doc-3'],
    healthScore: 94,
    healthScoreLevel: HealthScoreLevel.EXCELLENT,
    healthIssues: ['Acknowledgement rate at 82% (target: 90%)'],
    createdBy: 'user-1',
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'doc-2',
    libraryId: 'lib-1',
    tenantId: 'demo-tenant',
    documentNumber: 'SOP-HR-2026-002',
    title: 'Employee Onboarding Checklist',
    type: DocumentType.FORM,
    status: DocumentStatus.PUBLISHED,
    currentVersion: '2.1',
    versionId: 'ver-2-2',
    category: 'Onboarding',
    tags: ['onboarding', 'new hire', 'checklist', 'orientation'],
    department: 'Human Resources',
    owner: 'user-1',
    contributors: ['user-1'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-002',
    sourceFileName: 'Employee_Onboarding_Checklist.xlsx',
    sourceFileUrl: 'https://demo-sharepoint.com/sites/hr/Employee_Onboarding_Checklist.xlsx',
    fileSize: 128000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    complianceStandard: ComplianceStandard.ISO_9001,
    requiresApproval: true,
    requiresAcknowledgement: false,
    approvedDate: new Date('2026-01-10'),
    publishedDate: new Date('2026-01-10'),
    nextReviewDate: new Date('2027-01-10'),
    relatedDocuments: ['doc-1'],
    healthScore: 88,
    healthScoreLevel: HealthScoreLevel.GOOD,
    healthIssues: [],
    createdBy: 'user-1',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'doc-3',
    libraryId: 'lib-1',
    tenantId: 'demo-tenant',
    documentNumber: 'SOP-HR-2025-010',
    title: 'Performance Review Process',
    type: DocumentType.SOP,
    status: DocumentStatus.EXPIRED,
    currentVersion: '1.5',
    versionId: 'ver-3-1',
    category: 'Performance Management',
    tags: ['performance review', 'annual review', 'feedback'],
    department: 'Human Resources',
    owner: 'user-1',
    contributors: ['user-1', 'user-6'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-003',
    sourceFileName: 'Performance_Review_Process.docx',
    fileSize: 198000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    complianceStandard: ComplianceStandard.ISO_9001,
    requiresApproval: true,
    requiresAcknowledgement: true,
    approvedDate: new Date('2025-01-15'),
    publishedDate: new Date('2025-01-15'),
    expirationDate: new Date('2026-01-15'),
    nextReviewDate: new Date('2026-01-15'),
    relatedDocuments: [],
    healthScore: 28,
    healthScoreLevel: HealthScoreLevel.CRITICAL,
    healthIssues: ['Document expired 60 days ago', 'Review overdue', 'No action taken'],
    createdBy: 'user-1',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2025-01-15'),
  },

  // IT Security Library - Various Statuses
  {
    id: 'doc-4',
    libraryId: 'lib-2',
    tenantId: 'demo-tenant',
    documentNumber: 'POL-IT-2025-008',
    title: 'Data Security & Privacy Policy',
    type: DocumentType.POLICY,
    status: DocumentStatus.IN_REVIEW,
    currentVersion: '2.1',
    versionId: 'ver-4-1',
    category: 'Information Security',
    tags: ['data security', 'privacy', 'gdpr', 'encryption'],
    department: 'Information Technology',
    owner: 'user-2',
    contributors: ['user-2', 'user-8'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-004',
    sourceFileName: 'Data_Security_Privacy_Policy_v2.1.docx',
    fileSize: 312000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    aiSuggestedTags: ['data protection', 'privacy', 'gdpr', 'encryption', 'access control'],
    aiSuggestedCategory: 'Information Security',
    aiSuggestedReviewers: ['user-3', 'user-8'], // Legal + Compliance
    aiContentSummary: 'Comprehensive policy covering data classification, encryption requirements, access controls, privacy compliance (GDPR), and incident response procedures.',
    complianceStandard: ComplianceStandard.SOC_2,
    requiresApproval: true,
    requiresAcknowledgement: true,
    nextReviewDate: new Date('2027-04-01'),
    relatedDocuments: ['doc-5', 'doc-6'],
    healthScore: 72,
    healthScoreLevel: HealthScoreLevel.FAIR,
    healthIssues: ['In review for 2 days (SLA: 5 days)', 'Missing QA approval'],
    createdBy: 'user-2',
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2026-03-13'),
  },
  {
    id: 'doc-5',
    libraryId: 'lib-2',
    tenantId: 'demo-tenant',
    documentNumber: 'POL-IT-2026-015',
    title: 'Password Management Standard',
    type: DocumentType.POLICY,
    status: DocumentStatus.PUBLISHED,
    currentVersion: '1.0',
    versionId: 'ver-5-1',
    category: 'Access Control',
    tags: ['password', 'authentication', 'security', 'MFA'],
    department: 'Information Technology',
    owner: 'user-2',
    contributors: ['user-2'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-005',
    sourceFileName: 'Password_Management_Standard.pdf',
    fileSize: 156000,
    mimeType: 'application/pdf',
    complianceStandard: ComplianceStandard.SOC_2,
    requiresApproval: true,
    requiresAcknowledgement: true,
    approvedDate: new Date('2026-02-20'),
    publishedDate: new Date('2026-02-20'),
    nextReviewDate: new Date('2027-02-20'),
    relatedDocuments: ['doc-4'],
    healthScore: 96,
    healthScoreLevel: HealthScoreLevel.EXCELLENT,
    healthIssues: [],
    createdBy: 'user-2',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'doc-6',
    libraryId: 'lib-2',
    tenantId: 'demo-tenant',
    documentNumber: 'POL-IT-2026-018',
    title: 'Incident Response Plan',
    type: DocumentType.PROTOCOL,
    status: DocumentStatus.DRAFT,
    currentVersion: '1.0',
    versionId: 'ver-6-1',
    category: 'Security Operations',
    tags: ['incident response', 'security', 'breach', 'forensics'],
    department: 'Information Technology',
    owner: 'user-2',
    contributors: ['user-2', 'user-8'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-006',
    sourceFileName: 'Incident_Response_Plan_DRAFT.docx',
    fileSize: 421000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    aiSuggestedTags: ['incident response', 'security breach', 'forensics', 'disaster recovery'],
    aiSuggestedReviewers: ['user-3', 'user-4', 'user-8'],
    complianceStandard: ComplianceStandard.SOC_2,
    requiresApproval: true,
    requiresAcknowledgement: true,
    relatedDocuments: ['doc-4'],
    healthScore: 45,
    healthScoreLevel: HealthScoreLevel.POOR,
    healthIssues: ['Still in draft status', 'No approval workflow started', 'Created 15 days ago'],
    createdBy: 'user-2',
    createdAt: new Date('2026-02-28'),
    updatedAt: new Date('2026-03-10'),
  },

  // Quality Management Library
  {
    id: 'doc-7',
    libraryId: 'lib-3',
    tenantId: 'demo-tenant',
    documentNumber: 'QMS-2026-001',
    title: 'Document Control Procedure',
    type: DocumentType.SOP,
    status: DocumentStatus.PUBLISHED,
    currentVersion: '2.0',
    versionId: 'ver-7-1',
    category: 'Quality Management',
    tags: ['document control', 'iso 9001', 'quality', 'procedures'],
    department: 'Quality Assurance',
    owner: 'user-5',
    contributors: ['user-5', 'user-8'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-007',
    sourceFileName: 'Document_Control_Procedure.docx',
    fileSize: 289000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    complianceStandard: ComplianceStandard.ISO_9001,
    requiresApproval: true,
    requiresAcknowledgement: true,
    approvedDate: new Date('2026-01-05'),
    publishedDate: new Date('2026-01-05'),
    nextReviewDate: new Date('2027-01-05'),
    relatedDocuments: [],
    healthScore: 92,
    healthScoreLevel: HealthScoreLevel.EXCELLENT,
    healthIssues: [],
    createdBy: 'user-5',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2026-01-05'),
  },

  // General Library - Ghost Document Example
  {
    id: 'doc-8',
    libraryId: 'lib-4',
    tenantId: 'demo-tenant',
    documentNumber: 'DOC-2025-034',
    title: 'Q4 2025 Town Hall Presentation',
    type: DocumentType.OTHER,
    status: DocumentStatus.PUBLISHED,
    currentVersion: '1.0',
    versionId: 'ver-8-1',
    category: 'Communications',
    tags: ['town hall', 'presentation', 'quarterly'],
    department: 'Executive',
    owner: 'user-4',
    contributors: ['user-4'],
    sourceProvider: 'microsoft365',
    sourceFileId: 'ms365-file-008',
    sourceFileName: 'Q4_2025_Town_Hall.pptx',
    fileSize: 8400000,
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    complianceStandard: ComplianceStandard.NONE,
    requiresApproval: false,
    requiresAcknowledgement: false,
    publishedDate: new Date('2025-12-15'),
    relatedDocuments: [],
    healthScore: 35,
    healthScoreLevel: HealthScoreLevel.POOR,
    healthIssues: [
      'Ghost document detected (only 8% viewed it)',
      'Low engagement despite publication',
      'No acknowledgements tracked',
    ],
    createdBy: 'user-4',
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2025-12-15'),
  },
];

// ============================================================================
// APPROVAL WORKFLOWS
// ============================================================================

export const MOCK_WORKFLOWS: ApprovalWorkflow[] = [
  {
    id: 'workflow-1',
    libraryId: 'lib-1',
    tenantId: 'demo-tenant',
    name: 'Standard SOP Approval',
    description: '4-stage approval process for HR SOPs and policies',
    isDefault: true,
    documentTypes: [DocumentType.SOP, DocumentType.POLICY],
    stages: [
      {
        id: 'stage-1-1',
        workflowId: 'workflow-1',
        name: 'Tech Review',
        order: 1,
        type: ApprovalStageType.SEQUENTIAL,
        approvers: ['user-2'],
        requiredApprovals: 1,
        allowComments: true,
        requireComments: false,
        slaDays: 2,
      },
      {
        id: 'stage-1-2',
        workflowId: 'workflow-1',
        name: 'Compliance Review',
        order: 2,
        type: ApprovalStageType.PARALLEL,
        approvers: ['user-5', 'user-8'],
        requiredApprovals: 2,
        allowComments: true,
        requireComments: false,
        slaDays: 3,
      },
      {
        id: 'stage-1-3',
        workflowId: 'workflow-1',
        name: 'Legal Review',
        order: 3,
        type: ApprovalStageType.SEQUENTIAL,
        approvers: ['user-3'],
        requiredApprovals: 1,
        allowComments: true,
        requireComments: true,
        slaDays: 2,
      },
      {
        id: 'stage-1-4',
        workflowId: 'workflow-1',
        name: 'Executive Approval',
        order: 4,
        type: ApprovalStageType.SEQUENTIAL,
        approvers: ['user-4'],
        requiredApprovals: 1,
        allowComments: true,
        requireComments: false,
        slaDays: 1,
      },
    ],
    allowDelegation: true,
    escalationDays: 7,
    escalationRecipients: ['user-1', 'user-4'],
    createdBy: 'user-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-06-20'),
    isActive: true,
  },
  {
    id: 'workflow-2',
    libraryId: 'lib-2',
    tenantId: 'demo-tenant',
    name: 'IT Security Fast-Track',
    description: '2-stage approval for IT security policies',
    isDefault: true,
    documentTypes: [DocumentType.POLICY],
    categories: ['Information Security', 'Access Control'],
    stages: [
      {
        id: 'stage-2-1',
        workflowId: 'workflow-2',
        name: 'Security Review',
        order: 1,
        type: ApprovalStageType.SEQUENTIAL,
        approvers: ['user-2'],
        requiredApprovals: 1,
        allowComments: true,
        requireComments: false,
        slaDays: 3,
      },
      {
        id: 'stage-2-2',
        workflowId: 'workflow-2',
        name: 'Compliance Approval',
        order: 2,
        type: ApprovalStageType.SEQUENTIAL,
        approvers: ['user-8'],
        requiredApprovals: 1,
        allowComments: true,
        requireComments: false,
        slaDays: 2,
      },
    ],
    allowDelegation: false,
    escalationDays: 5,
    escalationRecipients: ['user-2'],
    createdBy: 'user-2',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2025-08-15'),
    isActive: true,
  },
  {
    id: 'workflow-3',
    libraryId: 'lib-3',
    tenantId: 'demo-tenant',
    name: 'QMS Simple Approval',
    description: '1-stage approval for quality documentation',
    isDefault: true,
    documentTypes: [DocumentType.SOP, DocumentType.WORK_INSTRUCTION],
    stages: [
      {
        id: 'stage-3-1',
        workflowId: 'workflow-3',
        name: 'Quality Manager Approval',
        order: 1,
        type: ApprovalStageType.SEQUENTIAL,
        approvers: ['user-5'],
        requiredApprovals: 1,
        allowComments: true,
        requireComments: false,
        slaDays: 5,
      },
    ],
    allowDelegation: true,
    escalationDays: 10,
    escalationRecipients: ['user-4'],
    createdBy: 'user-5',
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2025-06-01'),
    isActive: true,
  },
];

// ============================================================================
// COMPLIANCE GAPS
// ============================================================================

export const MOCK_COMPLIANCE_GAPS: ComplianceGap[] = [
  {
    id: 'gap-1',
    tenantId: 'demo-tenant',
    severity: 'critical',
    type: 'expired_document',
    documentId: 'doc-3',
    libraryId: 'lib-1',
    title: 'Performance Review Process Expired',
    description: 'Document SOP-HR-2025-010 expired 60 days ago and has not been reviewed or renewed.',
    recommendation: 'Immediately review and update the document, or archive if no longer needed.',
    isResolved: false,
    detectedAt: new Date('2026-03-15'),
    detectedBy: 'system',
  },
  {
    id: 'gap-2',
    tenantId: 'demo-tenant',
    severity: 'high',
    type: 'missing_approval',
    documentId: 'doc-4',
    libraryId: 'lib-2',
    title: 'Data Security Policy Missing QA Approval',
    description: 'POL-IT-2025-008 is in review but missing required Quality Assurance approval.',
    recommendation: 'Route document to QA team for compliance review before final approval.',
    isResolved: false,
    detectedAt: new Date('2026-03-13'),
    detectedBy: 'ai',
  },
  {
    id: 'gap-3',
    tenantId: 'demo-tenant',
    severity: 'medium',
    type: 'low_acknowledgement',
    documentId: 'doc-1',
    libraryId: 'lib-1',
    title: 'Remote Work Policy Low Acknowledgement Rate',
    description: 'SOP-HR-2026-001 has only 82% acknowledgement rate (target: 90%).',
    recommendation: 'Send reminder notifications to employees who have not acknowledged the policy.',
    isResolved: false,
    detectedAt: new Date('2026-03-10'),
    detectedBy: 'system',
  },
  {
    id: 'gap-4',
    tenantId: 'demo-tenant',
    severity: 'medium',
    type: 'orphaned_document',
    documentId: 'doc-8',
    libraryId: 'lib-4',
    title: 'Q4 Town Hall Presentation is a Ghost Document',
    description: 'DOC-2025-034 was published but only 8% of intended audience viewed it.',
    recommendation: 'Re-promote the document or archive if no longer relevant.',
    isResolved: false,
    detectedAt: new Date('2026-02-01'),
    detectedBy: 'ai',
  },
];

// ============================================================================
// MOCK ACKNOWLEDGEMENTS
// ============================================================================

export const generateMockAcknowledgements = (documentId: string): DocumentAcknowledgement[] => {
  const allUsers = DEMO_USERS;
  const acknowledgementRate = documentId === 'doc-1' ? 0.82 : 0.95;
  
  return allUsers.map((user, index) => ({
    id: `ack-${documentId}-${user.id}`,
    documentId,
    versionId: 'ver-1-3', // Current version
    tenantId: 'demo-tenant',
    userId: user.id,
    status: index < allUsers.length * acknowledgementRate 
      ? AcknowledgementStatus.ACKNOWLEDGED 
      : AcknowledgementStatus.PENDING,
    sentAt: new Date('2026-02-16'),
    acknowledgedAt: index < allUsers.length * acknowledgementRate 
      ? new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000) 
      : undefined,
    dueDate: new Date('2026-03-16'),
    isTrainingRequired: true,
    trainingCompleted: index < allUsers.length * acknowledgementRate,
    trainingCompletedAt: index < allUsers.length * acknowledgementRate 
      ? new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000) 
      : undefined,
  }));
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export const getLibraryById = (id: string): DocumentLibrary | undefined => {
  return MOCK_LIBRARIES.find(lib => lib.id === id);
};

export const getDocumentById = (id: string): ControlledDocument | undefined => {
  return MOCK_DOCUMENTS.find(doc => doc.id === id);
};

export const getDocumentsByLibraryId = (libraryId: string): ControlledDocument[] => {
  return MOCK_DOCUMENTS.filter(doc => doc.libraryId === libraryId);
};

export const getWorkflowsByLibraryId = (libraryId: string): ApprovalWorkflow[] => {
  return MOCK_WORKFLOWS.filter(workflow => workflow.libraryId === libraryId);
};

export const getUserById = (id: string): DemoUser | undefined => {
  return DEMO_USERS.find(user => user.id === id);
};

export const simulateApprovalDelay = (callback: () => void, delayMs: number = 3000): void => {
  setTimeout(callback, delayMs);
};
