import { motion as Motion, AnimatePresence } from "motion/react";
import { X, AlertTriangle, Shield, Send, FileText } from "lucide-react";

interface RemediationBriefProps {
  isOpen: boolean;
  onClose: () => void;
  reason?: 'STEWARD_ACCESS_GAP' | 'EXTERNAL_SHARE' | 'OWNERSHIP_UNKNOWN';
  workspace: {
    name: string;
    path?: string;
    steward?: string;
  };
}

export function RemediationBrief({ isOpen, onClose, reason = 'STEWARD_ACCESS_GAP', workspace }: RemediationBriefProps) {
  const handleRequestAccess = () => {
    const packet = [
      `Access Request Packet: ${workspace.name}`,
      '',
      `Justification: As designated steward for "${workspace.name}", I require native access to maintain operational integrity, validate ownership metadata, and ensure compliant handoff procedures.`,
      '',
      `Workspace Path: ${workspace.path || 'N/A'}`,
      `Requested By: ${workspace.steward || 'Current User'}`,
      `Request Date: ${new Date().toLocaleDateString()}`,
      '',
      'Generated by Aethos Integrity Intelligence',
    ].join('\n');

    void navigator.clipboard?.writeText(packet);
    const toast = (window as any).toast;
    if (toast?.success) {
      toast.success('Access request packet copied to clipboard');
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <Motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
            onClick={onClose}
          />

          <Motion.div
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 25, stiffness: 200 }}
            className="fixed right-0 top-0 bottom-0 w-full max-w-2xl bg-[#0B0F19] border-l border-white/10 shadow-2xl z-50 overflow-y-auto custom-scrollbar"
          >
            <div className="sticky top-0 bg-[#0B0F19] border-b border-white/10 px-8 py-6 flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-black uppercase tracking-tight text-white">
                  Remediation Brief
                </h2>
                <p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mt-1">
                  Access gap detected
                </p>
              </div>
              <button
                onClick={onClose}
                className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 transition-colors"
              >
                <X className="w-5 h-5 text-white" />
              </button>
            </div>

            <div className="p-8 space-y-8">
              <div className="bg-amber-950/20 border border-amber-900/30 rounded-xl p-6">
                <div className="flex items-start gap-4">
                  <div className="p-3 rounded-full bg-amber-500/20 border border-amber-500/30">
                    <AlertTriangle className="w-6 h-6 text-amber-400" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-sm font-black uppercase tracking-widest text-white mb-2">
                      Steward Access Gap
                    </h3>
                    <p className="text-sm leading-6 text-slate-400">
                      You are designated as the steward for this workspace but currently
                      lack native access permissions. This creates a blind spot in your
                      stewardship coverage.
                    </p>
                  </div>
                </div>
              </div>

              <div>
                <h3 className="text-sm font-black uppercase tracking-widest text-white mb-4 flex items-center gap-2">
                  <Shield className="w-5 h-5 text-[#1AFFFF]" />
                  Reason Code
                </h3>
                <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-[#1AFFFF]/10 border border-[#1AFFFF]/30">
                  <span className="text-xs font-black uppercase tracking-widest text-[#1AFFFF]">
                    {reason}
                  </span>
                </div>
              </div>

              <div>
                <h3 className="text-sm font-black uppercase tracking-widest text-white mb-4">
                  Risk Summary
                </h3>
                <div className="space-y-3">
                  {[
                    {
                      title: "Stewardship Integrity",
                      description: "Unable to verify content quality, ownership metadata, or usage patterns"
                    },
                    {
                      title: "Handoff Vulnerability",
                      description: "If current owner departs, knowledge transfer will be incomplete"
                    },
                    {
                      title: "Compliance Gap",
                      description: "Cannot audit or certify workspace contents per policy requirements"
                    }
                  ].map((risk, i) => (
                    <div key={i} className="flex items-start gap-3 p-4 bg-white/[0.03] rounded-lg border border-white/10">
                      <div className="w-2 h-2 rounded-full bg-amber-400 mt-2" />
                      <div className="flex-1">
                        <div className="text-xs font-black uppercase tracking-widest text-white mb-1">
                          {risk.title}
                        </div>
                        <div className="text-xs leading-5 text-slate-400">
                          {risk.description}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <h3 className="text-sm font-black uppercase tracking-widest text-white mb-4">
                  Workspace Details
                </h3>
                <div className="bg-white/[0.03] rounded-lg p-4 space-y-2 text-sm border border-white/10">
                  <div className="flex justify-between">
                    <span className="text-slate-500">Name:</span>
                    <span className="font-black text-white">{workspace.name}</span>
                  </div>
                  {workspace.path && (
                    <div className="flex justify-between">
                      <span className="text-slate-500">Path:</span>
                      <span className="font-mono text-xs text-slate-300">{workspace.path}</span>
                    </div>
                  )}
                  {workspace.steward && (
                    <div className="flex justify-between">
                      <span className="text-slate-500">Current Steward:</span>
                      <span className="font-black text-white">{workspace.steward}</span>
                    </div>
                  )}
                </div>
              </div>

              <div>
                <h3 className="text-sm font-black uppercase tracking-widest text-white mb-4">
                  Recommended Action
                </h3>
                <p className="text-sm leading-6 text-slate-400 mb-4">
                  Request native access to this workspace to fulfill your stewardship
                  responsibilities. This will enable continuous monitoring, quality
                  validation, and seamless ownership transitions.
                </p>

                <div className="bg-white/[0.03] border border-white/10 rounded-xl p-6">
                  <div className="flex items-center gap-2 mb-3">
                    <FileText className="w-4 h-4 text-[#1AFFFF]" />
                    <h4 className="text-xs font-black uppercase tracking-widest text-white">
                      Access Request Packet
                    </h4>
                  </div>
                  <div className="bg-black/40 rounded-lg p-4 mb-4 text-xs font-mono leading-6 text-slate-300 border border-white/5">
                    <div className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">
                      Request Justification:
                    </div>
                    <div>
                      As designated steward for "{workspace.name}", I require native
                      access to maintain operational integrity, validate ownership
                      metadata, and ensure compliant handoff procedures.
                    </div>
                  </div>

                  <button
                    onClick={handleRequestAccess}
                    className="w-full min-h-[48px] rounded-xl bg-[#1AFFFF] text-[#0B0F19] hover:bg-white transition-colors flex items-center justify-center gap-2 text-xs font-black uppercase tracking-widest"
                  >
                    <Send className="w-4 h-4" />
                    Copy Access Request
                  </button>
                </div>
              </div>

              <div className="pt-6 border-t border-white/10">
                <p className="text-[10px] leading-5 text-slate-500">
                  This brief was generated by Aethos Integrity Intelligence on{" "}
                  {new Date().toLocaleDateString()} based on current stewardship
                  assignments and permission mappings.
                </p>
              </div>
            </div>
          </Motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
