-- ============================================================================
-- Pending Metadata Suggestions
-- ============================================================================
-- V1.5 foundation: stage generated metadata intelligence for human review
-- before writing final AI fields or publishing source-system metadata changes.

CREATE TABLE IF NOT EXISTS metadata_suggestions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  file_id UUID REFERENCES files(id) ON DELETE CASCADE,
  suggestion_type TEXT NOT NULL CHECK (suggestion_type IN ('title', 'tag', 'category', 'summary', 'content_enrichment')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'edited', 'rejected', 'blocked', 'superseded')),
  confidence TEXT CHECK (confidence IN ('high', 'medium', 'low')),
  source TEXT NOT NULL DEFAULT 'aethos',
  source_signals TEXT[] DEFAULT '{}',
  rationale TEXT,
  suggested_value JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata JSONB DEFAULT '{}'::jsonb,
  generated_by UUID REFERENCES users(id) ON DELETE SET NULL,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_by UUID REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_metadata_suggestions_tenant_status
  ON metadata_suggestions(tenant_id, status, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_metadata_suggestions_file
  ON metadata_suggestions(tenant_id, file_id, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_metadata_suggestions_type
  ON metadata_suggestions(tenant_id, suggestion_type, status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_metadata_suggestions_pending_source_file
  ON metadata_suggestions(tenant_id, file_id, suggestion_type, source)
  WHERE status = 'pending';

ALTER TABLE metadata_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY metadata_suggestions_tenant_isolation ON metadata_suggestions
  FOR ALL USING (
    tenant_id = current_setting('app.current_tenant_id', true)::uuid
  );

COMMENT ON TABLE metadata_suggestions IS 'Pending review-first metadata suggestions generated by Aethos before approved metadata writeback';
